# Generated by Django 5.1.1 on 2024-10-04 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0002_remove_event_updated_at_event_author_event_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ref', models.CharField(blank=True, max_length=200)),
                ('verified', models.BooleanField(default=False)),
                ('event', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
    ]
